name: Demo Workflow

on:
  push:
    branches: [ main ]

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo " Hello from GitHub Actions!"
