# This is the name that will appear as the accordion title in your UI
name: Docs Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Deploy Documentation
        run: |
          echo "Building documentation..."
          sleep 5 # Simulate a build step
          echo "✅ Documentation deployed successfully!"
          exit 0
