# Name for the accordion title in your UI
name: webapp 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run failing tests
        run: |
          echo "❌ Simulating a test failure in the Node.js environment."
          exit 1

